### PR TITLE
Removed the trim function: Issue #35

### PR DESCRIPTION
**Pull request by Aspireve**

### CODE REVIEW

**Comment by AsaiToshiya** [comment]
Other than that, you need to remove all the trim.

**Comment by Aspireve** [comment]
Yup sure

**Comment by Aspireve** [comment]
I removed all the trim functions from the program
Hope it helps!!

**Comment by AsaiToshiya** [comment]
Probably this change will not work properly.

They have syntax error.

**Comment by AsaiToshiya** [comment]
@Aspireve sorry closed this PR after 7 days with no activity.

**Pull request closed without merging**
