### PR TITLE
Display "Empty" for empty notes in the note list #17

### PR DESCRIPTION
**Pull request by Aspireve**
The following code prints empty on the textarea when it is empty
Things I attempted before taking this path towards the solution:
- I tried changing value in list **only** however that wasn't possible as whenever I changes value in list the change would show up in text area
- I tried setting changing it into file but whenever I did that the change would again still appear in the text area as well
> Warning: This method of solving this problem can cause multiple recursions: 

1: When the file opens it directly shows "Empty" as default text
image

2: if the user goes on to clear the text one-by-one then the user will again get empty printed on his textarea
N - Google Chrome 2022-07-23 02-03-41

3: The only way to modify the content is to select the text and then directly start typing
N - Google Chrome 2022-07-23 02-03-55

Do review the file and tell if any more changes are needed, THANK YOU!!

### CODE REVIEW

**Review by AsaiToshiya — COMMENTED** [review]
I don't want to display "Empty" in the textarea, only the note list.

**Comment by AsaiToshiya** [comment]
I think you should add a computed property and use it in the note list.

**Comment by Aspireve** [comment]
Oh I'll try doing that then,

**Comment by Aspireve** [comment]
Hey @AsaiToshiya I guess I found a way, was quite difficult for me as I don't know muck about vue but I guess i did it
It doesn't use any new computed property though. Ill make the pull request soon

**Comment by Aspireve** [comment]
It works something like this, is this fine
N - Google Chrome 2022-07-23 15-57-59

**Comment by Aspireve** [comment]
Hey @AsaiToshiya I updated this pull request, hope you can see it and verify it.
Do review it and tell me if anything more needs to be changed

**Comment by Aspireve** [comment]
The changes I made:
- I added a new variable noteName to the newNote object which updates when the text updates
- when text is null it switches to Empty (also treats Space and Enter as null) and when text has something in it, it switches to the text in the text variable
- Also changed the variable which is shown as the name of the note, it now shows the note name as noteName variable whose functionality is as explained above 

Example of how it works
-
N - Google Chrome 2022-07-23 16-20-25

**Review by AsaiToshiya — APPROVED** [review]
Your way to do it works fine too, but increases amount of data to store.

Anyway, I will merge this PR.

**Pull request merged**
